{% set version = "1.3.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-wdpar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/wdpar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wdpar/wdpar_{{ version }}.tar.gz
  sha256: 06655bd4979f802854ca2f0c178135bb407241796063c3ef90b397721e2fc056

build:
  skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertthat >=0.2.0
    - r-chromote >=0.2.0
    - r-cli >=1.0.1
    - r-countrycode >=1.1.0
    - r-curl >=3.2
    - r-httr >=1.3.1
    - r-lwgeom >=0.2_1
    - r-pingr >=1.1.2
    - r-progress >=1.2.0
    - r-rappdirs >=0.3.1
    - r-sf >=1.0_13
    - r-tibble >=2.1.3
    - r-withr >=3.0.0
    - r-xml2 >=1.2.0
  run:
    - r-base
    - r-assertthat >=0.2.0
    - r-chromote >=0.2.0
    - r-cli >=1.0.1
    - r-countrycode >=1.1.0
    - r-curl >=3.2
    - r-httr >=1.3.1
    - r-lwgeom >=0.2_1
    - r-pingr >=1.1.2
    - r-progress >=1.2.0
    - r-rappdirs >=0.3.1
    - r-sf >=1.0_13
    - r-tibble >=2.1.3
    - r-withr >=3.0.0
    - r-xml2 >=1.2.0

test:
  commands:
    - $R -e "library('wdpar')"           # [not win]
    - "\"%R%\" -e \"library('wdpar')\""  # [win]

about:
  home: https://prioritizr.github.io/wdpar/
  dev_url: https://github.com/prioritizr/wdpar
  license: GPL-3.0-only
  summary: Fetch and clean data from the World Database on Protected Areas (WDPA). Data is obtained from Protected Planet <https://www.protectedplanet.net/en>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
